
# Buttons that can be used anywhere here
global buttons:

menu1:

  # There's two types paged & normal
  type: paged

  # If paged there's two placeholders for title: %currentPage%/%availablePages%
  title: "&eExample Menu Title"

  # Layout is a way to form your GUI this also defines inventory size
  # If you want AIR the layout id for AIR is A
  layout:
    - "XXXXXXXXX"
    - "AAAAFAAAA"
    - ""
    - "XXXPXNXXB"

  buttons:

    # This is the layout ID
    "X":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: fillable
      material: YELLOW_STAINED_GLASS_PANE

    "N":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: swappable
      material: arrow
      display name: "&e>>"
      on swap:
        material: black_stained_glass_pane

      on click:
        execute action: "next page"

    "P":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: swappable
      material: arrow
      display name: "&e<<"
      on swap:
        material: black_stained_class_pane

      on click:
        execute action: "previous page"

    "F":
      type: fillable
      material: air
      on fill:
        execute action: "onFill"

      on empty:
        execute action: "onEmpty"

    "show player":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      display name: "&e%player%"
      type: normal
      template: true
      material: player_head

      on click:
        execute action: "show player kills"