menu1:

  # There's two types paged & normal
  type: paged
  title: "&eExample Menu Title"

  # Layout is a way to form your GUI this also defines inventory size
  layout:
    - "XXXXXXXXX"
    - ""
    - ""
    - "XXXPXNXXX"

  buttons:

    # This is the layout ID
    "X":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: filler
      material: YELLOW_STAINED_GLASS_PANE

    "N":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: swappable
      material: arrow
      display name: "&e>>"
      on swap:
        material: black_stained_glass_pane

      on click:
        execute action: "next page"

    "previous page":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: swappable
      layout id: "P"
      material: arrow
      display name: "&e<<"
      on swap:
        material: black_stained_class_pane

    "show player":
      # There's three types of buttons
      # filler = Dummy button
      # normal = An ordinary button
      # swappable = A button that has a swappable itemStack, it's mostly used for nextPage, previousPage to replace when they're not needed
      type: normal
      template: true
      layout id: "Q"
      material: player_head



